# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NVActivityIndicatorView' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'lottie-ios', '2.1.3'

  # Pods for NVActivityIndicatorView

end

target 'NVActivityIndicatorViewAppExtension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NVActivityIndicatorViewAppExtension

end
